all:
	zip -r com_helloworld-1.6-`basename $(CURDIR)`.zip admin site media helloworld.xml script.php ChangeLog LICENSE.txt -i "*.php" -i "*.html" -i "*.sql" -i "*.xml" -i "*.ini" -i "*.js" -i "*.css" -i "*.png"

